apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 10s

    route:
      group_by: ['alertname']
      group_wait: 3s
      receiver: 'telegram-critical'
      routes:
        - receiver: 'telegram-critical'
          match:
            severity: 'critical'
          continue: true

        - receiver: 'telegram-warning'
          match:
            severity: 'warning'
          active_time_intervals:
            - worktime
          continue: true

    receivers:
      - name: 'telegram-critical'
        telegram_configs:
          - bot_token: '7418992362:AAEDbA__h6YGouo-frLJ307ANHe2daYhbM'
            api_url: 'https://api.telegram.org'
            chat_id: 506645542
            parse_mode: 'HTML'
        
      - name: 'telegram-warning'
        telegram_configs:
          - bot_token: '7870061232:AAElvx9xla8_0Rj3_PwXpymxkj0anjIA3A'
            api_url: 'https://api.telegram.org'
            chat_id: 506645542
            parse_mode: 'HTML'

    time_intervals:
      - name: worktime
        time_intervals:
          - times:
            - start_time: 08:00
              end_time: 18:00
