apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'prober-oncall'
        static_configs:
          - targets: ['oncall-prober-service:1238']

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager-service:9093'
    
    rule_files:
      - /etc/prometheus/rules/*.yml
